### PR TITLE
initial project setup

### PR DESCRIPTION
**Pull request by King-Benx**
Delivers:
1. Linters
2. Workflows
3. Initial project setup

### CODE REVIEW

**Comment by didierganthier** [comment]
@King-Benx check on Slack, I messaged you. Also, open your Zoom app. 😉

**Review by didierganthier — COMMENTED** [review]
Hi <STUDENT_MENTION>,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.



## Invalid Code Review Request 🚫

- You have submitted a project with the linters test failing, it also seems like you're not using the React linters. 👀 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

**Review by franclobo — COMMENTED** [review]
Hi @King-Benx, 

terminator

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
Hi @King-Benx  🙋‍♂️, 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code

## :no_entry:  Invalid Code Review Request :no_entry: 

- [ ] I appreciate your great effort on this project :+1:. However, it is necessary to follow Gitflow instead of GitHub flow for this project. This is because Gitflow provides a more structured and organized approach to version control, which is essential for larger projects with multiple contributors. Gitflow also allows for easier maintenance and management of feature branches, releases, and hotfixes. Therefore, adhering to Gitflow will ensure a smoother and more efficient development process for this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready :inbox_tray: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Rustamxon7 — APPROVED** [review]
Hi @King-Benx, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Developer-512px-10

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
